name: dfl
channels:
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - _libgcc_mutex=0.1=main
  - autograd=1.2=py_1
  - binutils=2.36.1=hdd6e379_2
  - binutils_impl_linux-64=2.36.1=h193b22a_2
  - binutils_linux-64=2.36=hf3e587d_33
  - blas=1.0=mkl
  - c-compiler=1.1.2=h36c2ea0_0
  - ca-certificates=2021.10.8=ha878542_0
  - certifi=2021.5.30=py36h5fab9bb_0
  - cffi=1.14.0=py36h2e261b9_0
  - cudatoolkit=10.0.130=0
  - cudnn=7.6.5=cuda10.0_0
  - cvxpy=1.1.7=py36h831f99a_0
  - cvxpy-base=1.1.7=py36h7c3b610_0
  - cxx-compiler=1.1.2=h0efe328_0
  - cycler=0.10.0=py_1
  - dbus=1.13.2=h714fa37_1
  - ecos=2.0.7.post1=py36h6323ea4_0
  - expat=2.2.5=he1b5a44_1003
  - fontconfig=2.13.1=he4413a7_1000
  - freetype=2.9.1=h8a8886c_1
  - future=0.18.2=py36_1
  - gcc_impl_linux-64=7.5.0=hda68d29_13
  - gcc_linux-64=7.5.0=h47867f9_33
  - gettext=0.19.8.1=hc5be6a0_1002
  - glib=2.56.2=had28632_1001
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - gxx_impl_linux-64=7.5.0=h64c220c_13
  - gxx_linux-64=7.5.0=h555fc39_33
  - icu=58.2=hf484d3e_1000
  - intel-openmp=2019.4=243
  - jpeg=9b=h024ee3a_2
  - kernel-headers_linux-64=2.6.32=he073ed8_15
  - lapack=3.6.1=ha44fe06_2
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc=7.2.0=h69d50b8_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran=3.0.0=1
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libgomp=9.3.0=h5101ec6_17
  - libiconv=1.15=h516909a_1005
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.0.10=h2733197_2
  - libuuid=2.32.1=h14c3975_1000
  - libxcb=1.13=h14c3975_1002
  - libxml2=2.9.9=h13577e0_0
  - mkl=2019.4=243
  - mkl-service=2.3.0=py36he8ac12f_0
  - mkl_fft=1.3.0=py36h54f3939_0
  - mkl_random=1.1.0=py36hd6b4f25_0
  - ncurses=6.1=he6710b0_1
  - ninja=1.10.2=hff7bd54_1
  - numpy=1.19.2=py36h54aff64_0
  - numpy-base=1.19.2=py36hfa32c7d_0
  - openblas=0.3.3=h9ac9557_1001
  - openssl=1.1.1h=h516909a_0
  - osqp=0.6.1=py36h830a2c2_2
  - pcre=8.43=he6710b0_0
  - pip=21.0.1=py36h06a4308_0
  - proj=6.2.0=hc80f0dc_1
  - pthread-stubs=0.4=h14c3975_1001
  - pycparser=2.20=py_2
  - pyparsing=2.4.0=py_0
  - python=3.6.9=h265db76_0
  - python-dateutil=2.8.0=py_0
  - python_abi=3.6=2_cp36m
  - qt=5.6.3=h8bf5577_3
  - readline=7.0=h7b6447c_5
  - scs=2.0.2=py36h0290663_1000
  - setuptools=52.0.0=py36h06a4308_0
  - six=1.15.0=py36h06a4308_0
  - sqlite=3.30.0=h7b6447c_0
  - sysroot_linux-64=2.12=he073ed8_15
  - tk=8.6.9=hed695b0_1002
  - tqdm=4.32.2=py_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pip:
    - charset-normalizer==2.0.12
    - cloudpickle==1.6.0
    - cvxpylayers==0.1.5
    - dataclasses==0.8
    - decorator==4.4.2
    - diffcp==1.0.19
    - gym==0.18.3
    - idna==3.3
    - inflection==0.5.1
    - joblib==1.0.1
    - kiwisolver==1.3.1
    - matplotlib==3.3.4
    - metis==0.2a5
    - more-itertools==8.12.0
    - networkx==2.5.1
    - pandas==1.1.5
    - pillow==8.2.0
    - pybind11==2.9.0
    - pyglet==1.5.15
    - pytz==2021.1
    - quandl==3.7.0
    - requests==2.27.1
    - scikit-learn==0.24.2
    - scipy==1.5.4
    - seaborn==0.11.1
    - sklearn==0.0
    - threadpoolctl==2.1.0
    - torch==1.8.1
    - torchviz==0.0.2
    - typing-extensions==3.10.0.0
    - urllib3==1.26.9
